export const searchItems = [
  {
    title: "CS_KRISHI_10L",
    description: "Agriculture Drone with precision spraying and smart analytics.",
    image: "/drones/cs-krishi-images/cs-krishi.png",
    href: "/drones/cs_krishi_10L",
    type: "Product",
  },
  {
    title: "CS-Mamba",
    description: "Advanced surveillance drone for security and monitoring.",
    image: "/drones/cs-mamba-images/cs-mamba.png",
    href: "/drones/cs-mamba",
    type: "Product",
  },
  // {
  //   title: "CS-Bee",
  //   description: "Compact stealth spy drone for intelligence capture.",
  //   image: "/drones/cs-bee-images/cs-bee.png",
  //   href: "/drones/cs-bee",
  //   type: "Product",
  // },
  {
    title: "CS-Pride",
    description: "High-speed racing drone built for extreme performance.",
    image: "/drones/cs-pride-images/cs-pride.png",
    href: "/drones/cs-pride",
    type: "Product",
  },
  {
    title: "CS-Bheem",
    description: "Delivery drone designed for safe and fast last-mile logistics.",
    image: "/drones/cs-bheem-images/cs-bheem.png",
    href: "/drones/cs-bheem",
    type: "Product",
  },
  {
    title: "Agriculture Drone Service",
    description: "Precision crop spraying and farm intelligence solutions.",
    image: "/scroll/CS_KRISHI_10L.jpg",
    href: "/services",
    type: "Service",
  },
  {
    title: "Surveillance Drone Service",
    description: "Real-time aerial monitoring for security operations.",
    image: "/scroll/cs-mamba.jpg",
    href: "/services",
    type: "Service",
  },
  // {
  //   title: "Spy Drone",
  //   description: "Built for stealth missions with silent flight, compact design, and secure high-resolution intelligence capture.",
  //   image: "/scroll/cs-BEE.jpg",
  //   href: "/services",
  //   type: "Service",
  // },
  {
    title: "Racing Drone",
    description: "Experience extreme speed and control with high-thrust performance tuned for competitive racing.",
    image: "/scroll/CS-PRIDE.jpg",
    href: "/services",
    type: "Service",
  },
  {
    title: "Delivery Drone Service",
    description: "Enable fast last-mile delivery with payload stability, route automation, and safe drop precision.",
    image: "/scroll/CS-BHEEM.jpg",
    href: "/services",
    type: "Service",
  },
  // {
  //   title: "Powerline Inspection Service",
  //   description: "Drone-based inspection of transmission lines to ensure safety and operational efficiency.",
  //   image: "/services/powerline.jpg",
  //   href: "/services",
  //   type: "Service",
  // },
  // {
  //   title: "Solar Panel Inspection Service",
  //   description: "Thermal and visual drone inspection for optimized solar panel performance.",
  //   image: "/services/solar.jpg",
  //   href: "/services",
  //   type: "Service",
  // },
];